### ISSUE TITLE
Still empty

### ISSUE THREAD

**Issue by tjmonsi** [ArielDoria/CMSC198-Practicum-FinalReport#1]
I thought this was already filled :)

**Comment by ArielDoria** [comment]
Hi Sir,

I have already wiki pages at
https://github.com/ArielDoria/CMSC198-Practicum-FinalReport/wiki. Is there
any requirements that I need to do in my github account?

Regards,
Ariel

On Sun, Jul 19, 2015 at 9:18 AM, Toni-Jan Keith Monserrat <
notifications@github.com> wrote:

> I thought this was already filled :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArielDoria/CMSC198-Practicum-FinalReport/issues/1>.
>



-- 
Ariel Bituin Doria
2012-37192
BS Computer Science
